services:
  - name: deepseek-api
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "10000"
